import Head from "next/head";
import React, { Fragment, useState } from "react";
import Footer from "./Footer";
import Header from "./Header";
import Sidebar from "./Sidebar";

const Layout = ({children, title="Dashboard"}) => {
     //console.log("layout", title)
     const [mobileNavsidebar, setMobileNavsidebar] = useState(false);
     
  return (
    <Fragment>
      
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
          rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
          rel="stylesheet" />
      </Head>

       <div className="flex bg-gray-100 min-h-screen relative">
          <div className="flex-grow text-gray-800">
              {/*<Header />*/}
              {/*{children}*/}
              <div className="flex h-screen w-full bg-gray-800 " x-data="{openMenu:1}">
            <aside className="w-20 relative z-20 flex-shrink-0  px-2 overflow-y-auto bg-gradient-to-t from-violet-200 to-blue-400 sm:block">
                      <div className="mb-6">
                        <div className="flex justify-center">
                          <div className="w-14 h-14 rounded-full bg-gray-300 border-2 border-white mt-2">
                            <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0IgVI8ZYEVANweC5NdQ549waMZjNSHER_39BPOxxXvO3pDu4PJGfLlQr3DA&s"
                              className="rounded-full w-auto"
                            />
                          </div>
                        </div>

                        <div>
                          <ul className="mt-6 leading-10 px-4">
                            <li className="mb-3 p-2 rounded-md flex items-center justify-center bg-blue-400 cursor-pointer">
                              <i className="fas fa-align-left fa-sm text-white"></i>
                            </li>
                            <li className="mb-3 p-2 rounded-md flex items-center justify-center bg-pink-400 cursor-pointer">
                              <i className="fas fa-question-circle fa-sm text-white"></i>
                            </li>
                            
                            <li className="absolute bottom-0 mb-3 p-2 rounded-full flex items-center mx-auto bg-white cursor-pointer">
                              <i className="fas fa-power-off fa-sm text-indigo-600"></i>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </aside>
                     
                    {children}

              </div>
          </div>
      </div> 
        

    </Fragment>
  );
};

export default Layout;
